
server:
  port: 7001
eureka:
  instance:
    hostname:  127.0.0.1
  client:
    register-with-eureka: false #false表示不注册自己
    fetch-registry: false #false表示自己端就是注册中心，职责就是维护服务实例，并不需要检索服务
    service-url:
      #设置eureka服务交互地址，查询服务和注册服务都需要改地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
spring:
  application:
    name: eureka-server
